#!/bin/bash
# APIS Dataset Download Instructions
# Acute stroke paired CT-MRI/ADC with expert lesion labels
# Source: https://bivl2ab.uis.edu.co/challenges/apis
# Paper: https://doi.org/10.1038/s41598-024-71273-x

set -e

APIS_DIR="${1:-data/apis}"
mkdir -p "$APIS_DIR"/{raw,splits,preproc}

echo "====================================="
echo "APIS Dataset Setup Instructions"
echo "====================================="
echo ""
echo "Dataset: Acute Ischemic Stroke paired CT-MRI with lesion masks"
echo "Size: ~60 training pairs + 40 validation/test pairs"
echo ""
echo "⚠️  MANUAL REGISTRATION REQUIRED"
echo ""
echo "This dataset requires registration at the challenge portal before download."
echo ""
echo "====================================="
echo "Step-by-Step Instructions:"
echo "====================================="
echo ""
echo "1. Visit Challenge Portal:"
echo "   https://bivl2ab.uis.edu.co/challenges/apis"
echo ""
echo "2. Create an account / Sign in"
echo ""
echo "3. Accept the data use agreement"
echo ""
echo "4. Navigate to the 'Data' or 'Downloads' section"
echo ""
echo "5. Download the following files:"
echo "   - Training set (CT images)"
echo "   - Training set (ADC/MRI images)"
echo "   - Training set (Lesion masks - expert annotations)"
echo "   - Validation/Test sets (if available)"
echo ""
echo "6. Extract downloaded archives to:"
echo "   $APIS_DIR/raw/"
echo ""
echo "====================================="
echo "Expected Directory Structure:"
echo "====================================="
echo ""
echo "$APIS_DIR/"
echo "├── raw/"
echo "│   ├── ct/"
echo "│   │   ├── <case_001>/"
echo "│   │   │   └── ct.nii.gz (or DICOM series)"
echo "│   │   ├── <case_002>/"
echo "│   │   └── ..."
echo "│   ├── adc/"
echo "│   │   ├── <case_001>/"
echo "│   │   │   └── adc.nii.gz (or mri.nii.gz)"
echo "│   │   ├── <case_002>/"
echo "│   │   └── ..."
echo "│   └── lesion_masks/"
echo "│       ├── <case_001>.nii.gz"
echo "│       ├── <case_002>.nii.gz"
echo "│       └── ..."
echo "├── splits/"
echo "│   ├── train.txt"
echo "│   ├── val.txt"
echo "│   └── test.txt"
echo "└── preproc/"
echo "    └── (processed data will go here)"
echo ""
echo "====================================="
echo "After Download:"
echo "====================================="
echo ""
echo "1. If data is in DICOM format, convert to NIfTI:"
echo "   bash scripts/convert_dicom.sh $APIS_DIR/raw/ct/<case_id>"
echo ""
echo "2. Create train/val/test splits:"
echo "   python scripts/make_splits.py \\"
echo "       --data_dir $APIS_DIR/raw \\"
echo "       --output $APIS_DIR/splits \\"
echo "       --ratios 0.7 0.15 0.15 \\"
echo "       --seed 42"
echo ""
echo "3. Run preprocessing pipeline:"
echo "   bash workflow/03_preprocess_data.sh"
echo ""
echo "====================================="
echo "Reference Information:"
echo "====================================="
echo ""
echo "Paper:"
echo "  Diaz-Hurtado et al. (2024)"
echo "  'APIS: a paired CT-MRI dataset for ischemic stroke segmentation'"
echo "  Nature Scientific Reports"
echo "  DOI: 10.1038/s41598-024-71273-x"
echo ""
echo "Dataset Details:"
echo "  - Modalities: NCCT (non-contrast CT) + ADC/MRI"
echo "  - Target: Acute ischemic stroke lesions"
echo "  - Annotations: Expert radiologist segmentations"
echo "  - Use case: Image fusion with lesion-aware metrics"
echo ""
echo "====================================="
echo ""
echo "Setup directory created at: $APIS_DIR"
echo ""
echo "Please proceed with manual download from the challenge portal."
echo ""
